version: '3'

services:

    server:
        command: bash -c "
            python3 -m pip install grpcio grpcio-tools &&
            python3 server/server.py"
        image: python:latest
        volumes:
            - ./:/server
        container_name: server
        ports:
            - "5000:5000"
        networks:
            betweenContainers:
                ipv4_address: 172.20.0.10

    client1:
        command:  bash -c "
            python3 -m pip install grpcio grpcio-tools &&
            python3 client1/client.py"
        image: python:latest
        container_name: client1
        volumes:
            - ./:/client1
        depends_on: 
            - server
        networks:
            - betweenContainers
        stdin_open: true
        tty: true

    client2:
        command:  bash -c "
            python3 -m pip install grpcio grpcio-tools &&
            python3 client2/client.py"
        image: python:latest
        container_name: client2
        volumes:
            - ./:/client2
        depends_on:
            - server
        networks:
            - betweenContainers
        stdin_open: true
        tty: true

networks:
    betweenContainers:
        ipam:
            driver: default
            config:
            - subnet: 172.20.0.0/16
            # gateway: 172.20.0.1
            #iprange?
