# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensajeria.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mensajeria.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\242\002\004AUTH'),
  serialized_pb=_b('\n\x10mensajeria.proto\"\x17\n\x07newUser\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x0fresponseNewUser\x12\x10\n\x08response\x18\x01 \x01(\t\"A\n\tmsgToUser\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08receptor\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\'\n\x13responseCreationMsg\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1e\n\x0brequestList\x12\x0f\n\x07request\x18\x01 \x01(\t\" \n\x0cresponseList\x12\x10\n\x08nameList\x18\x01 \x01(\t\"\"\n\rrequestAllMsg\x12\x11\n\tuser_name\x18\x01 \x01(\t\"F\n\x0eresponseAllMsg\x12\x10\n\x08receptor\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\" \n\x0brequestUser\x12\x11\n\tuser_name\x18\x01 \x01(\t\"1\n\x0ewaitingMessage\x12\x0e\n\x06\x65misor\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\nrequestMsg\x12\x11\n\tuser_name\x18\x01 \x01(\t\"A\n\x0bresponseMsg\x12\x0e\n\x06\x65misor\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\x32\xa6\x02\n\nMensajeria\x12*\n\nCreateUser\x12\x08.newUser\x1a\x10.responseNewUser\"\x00\x12/\n\tMsgToUser\x12\n.msgToUser\x1a\x14.responseCreationMsg\"\x00\x12-\n\nObtainList\x12\x0c.requestList\x1a\r.responseList\"\x00\x30\x01\x12\x33\n\x0cObtainAllMsg\x12\x0e.requestAllMsg\x1a\x0f.responseAllMsg\"\x00\x30\x01\x12-\n\nWaitingMsg\x12\x0c.requestUser\x1a\x0f.waitingMessage\"\x00\x12(\n\x07ViewMsg\x12\x0b.requestMsg\x1a\x0c.responseMsg\"\x00\x30\x01\x42\x07\xa2\x02\x04\x41UTHb\x06proto3')
)




_NEWUSER = _descriptor.Descriptor(
  name='newUser',
  full_name='newUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='newUser.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_RESPONSENEWUSER = _descriptor.Descriptor(
  name='responseNewUser',
  full_name='responseNewUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='responseNewUser.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=80,
)


_MSGTOUSER = _descriptor.Descriptor(
  name='msgToUser',
  full_name='msgToUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='msgToUser.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receptor', full_name='msgToUser.receptor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='msgToUser.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=147,
)


_RESPONSECREATIONMSG = _descriptor.Descriptor(
  name='responseCreationMsg',
  full_name='responseCreationMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='responseCreationMsg.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=188,
)


_REQUESTLIST = _descriptor.Descriptor(
  name='requestList',
  full_name='requestList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='requestList.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=220,
)


_RESPONSELIST = _descriptor.Descriptor(
  name='responseList',
  full_name='responseList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nameList', full_name='responseList.nameList', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=254,
)


_REQUESTALLMSG = _descriptor.Descriptor(
  name='requestAllMsg',
  full_name='requestAllMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='requestAllMsg.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=290,
)


_RESPONSEALLMSG = _descriptor.Descriptor(
  name='responseAllMsg',
  full_name='responseAllMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receptor', full_name='responseAllMsg.receptor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='responseAllMsg.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='responseAllMsg.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=362,
)


_REQUESTUSER = _descriptor.Descriptor(
  name='requestUser',
  full_name='requestUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='requestUser.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=396,
)


_WAITINGMESSAGE = _descriptor.Descriptor(
  name='waitingMessage',
  full_name='waitingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emisor', full_name='waitingMessage.emisor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='waitingMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=447,
)


_REQUESTMSG = _descriptor.Descriptor(
  name='requestMsg',
  full_name='requestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='requestMsg.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=480,
)


_RESPONSEMSG = _descriptor.Descriptor(
  name='responseMsg',
  full_name='responseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emisor', full_name='responseMsg.emisor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='responseMsg.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='responseMsg.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=547,
)

DESCRIPTOR.message_types_by_name['newUser'] = _NEWUSER
DESCRIPTOR.message_types_by_name['responseNewUser'] = _RESPONSENEWUSER
DESCRIPTOR.message_types_by_name['msgToUser'] = _MSGTOUSER
DESCRIPTOR.message_types_by_name['responseCreationMsg'] = _RESPONSECREATIONMSG
DESCRIPTOR.message_types_by_name['requestList'] = _REQUESTLIST
DESCRIPTOR.message_types_by_name['responseList'] = _RESPONSELIST
DESCRIPTOR.message_types_by_name['requestAllMsg'] = _REQUESTALLMSG
DESCRIPTOR.message_types_by_name['responseAllMsg'] = _RESPONSEALLMSG
DESCRIPTOR.message_types_by_name['requestUser'] = _REQUESTUSER
DESCRIPTOR.message_types_by_name['waitingMessage'] = _WAITINGMESSAGE
DESCRIPTOR.message_types_by_name['requestMsg'] = _REQUESTMSG
DESCRIPTOR.message_types_by_name['responseMsg'] = _RESPONSEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

newUser = _reflection.GeneratedProtocolMessageType('newUser', (_message.Message,), {
  'DESCRIPTOR' : _NEWUSER,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:newUser)
  })
_sym_db.RegisterMessage(newUser)

responseNewUser = _reflection.GeneratedProtocolMessageType('responseNewUser', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSENEWUSER,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:responseNewUser)
  })
_sym_db.RegisterMessage(responseNewUser)

msgToUser = _reflection.GeneratedProtocolMessageType('msgToUser', (_message.Message,), {
  'DESCRIPTOR' : _MSGTOUSER,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:msgToUser)
  })
_sym_db.RegisterMessage(msgToUser)

responseCreationMsg = _reflection.GeneratedProtocolMessageType('responseCreationMsg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECREATIONMSG,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:responseCreationMsg)
  })
_sym_db.RegisterMessage(responseCreationMsg)

requestList = _reflection.GeneratedProtocolMessageType('requestList', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLIST,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:requestList)
  })
_sym_db.RegisterMessage(requestList)

responseList = _reflection.GeneratedProtocolMessageType('responseList', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSELIST,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:responseList)
  })
_sym_db.RegisterMessage(responseList)

requestAllMsg = _reflection.GeneratedProtocolMessageType('requestAllMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTALLMSG,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:requestAllMsg)
  })
_sym_db.RegisterMessage(requestAllMsg)

responseAllMsg = _reflection.GeneratedProtocolMessageType('responseAllMsg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEALLMSG,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:responseAllMsg)
  })
_sym_db.RegisterMessage(responseAllMsg)

requestUser = _reflection.GeneratedProtocolMessageType('requestUser', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTUSER,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:requestUser)
  })
_sym_db.RegisterMessage(requestUser)

waitingMessage = _reflection.GeneratedProtocolMessageType('waitingMessage', (_message.Message,), {
  'DESCRIPTOR' : _WAITINGMESSAGE,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:waitingMessage)
  })
_sym_db.RegisterMessage(waitingMessage)

requestMsg = _reflection.GeneratedProtocolMessageType('requestMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMSG,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:requestMsg)
  })
_sym_db.RegisterMessage(requestMsg)

responseMsg = _reflection.GeneratedProtocolMessageType('responseMsg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMSG,
  '__module__' : 'mensajeria_pb2'
  # @@protoc_insertion_point(class_scope:responseMsg)
  })
_sym_db.RegisterMessage(responseMsg)


DESCRIPTOR._options = None

_MENSAJERIA = _descriptor.ServiceDescriptor(
  name='Mensajeria',
  full_name='Mensajeria',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=550,
  serialized_end=844,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='Mensajeria.CreateUser',
    index=0,
    containing_service=None,
    input_type=_NEWUSER,
    output_type=_RESPONSENEWUSER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MsgToUser',
    full_name='Mensajeria.MsgToUser',
    index=1,
    containing_service=None,
    input_type=_MSGTOUSER,
    output_type=_RESPONSECREATIONMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ObtainList',
    full_name='Mensajeria.ObtainList',
    index=2,
    containing_service=None,
    input_type=_REQUESTLIST,
    output_type=_RESPONSELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ObtainAllMsg',
    full_name='Mensajeria.ObtainAllMsg',
    index=3,
    containing_service=None,
    input_type=_REQUESTALLMSG,
    output_type=_RESPONSEALLMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WaitingMsg',
    full_name='Mensajeria.WaitingMsg',
    index=4,
    containing_service=None,
    input_type=_REQUESTUSER,
    output_type=_WAITINGMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ViewMsg',
    full_name='Mensajeria.ViewMsg',
    index=5,
    containing_service=None,
    input_type=_REQUESTMSG,
    output_type=_RESPONSEMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MENSAJERIA)

DESCRIPTOR.services_by_name['Mensajeria'] = _MENSAJERIA

# @@protoc_insertion_point(module_scope)
