# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mensajeria_pb2 as mensajeria__pb2


class MensajeriaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/Mensajeria/CreateUser',
        request_serializer=mensajeria__pb2.newUser.SerializeToString,
        response_deserializer=mensajeria__pb2.responseNewUser.FromString,
        )
    self.MsgToUser = channel.stream_stream(
        '/Mensajeria/MsgToUser',
        request_serializer=mensajeria__pb2.msgToUser.SerializeToString,
        response_deserializer=mensajeria__pb2.msgFromUser.FromString,
        )
    self.ChangeReceptor = channel.unary_unary(
        '/Mensajeria/ChangeReceptor',
        request_serializer=mensajeria__pb2.ToUser.SerializeToString,
        response_deserializer=mensajeria__pb2.ToUserResponse.FromString,
        )
    self.ObtainList = channel.unary_stream(
        '/Mensajeria/ObtainList',
        request_serializer=mensajeria__pb2.requestList.SerializeToString,
        response_deserializer=mensajeria__pb2.responseList.FromString,
        )
    self.ObtainAllMsg = channel.unary_stream(
        '/Mensajeria/ObtainAllMsg',
        request_serializer=mensajeria__pb2.requestAllMsg.SerializeToString,
        response_deserializer=mensajeria__pb2.responseAllMsg.FromString,
        )


class MensajeriaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MsgToUser(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeReceptor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ObtainList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ObtainAllMsg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MensajeriaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=mensajeria__pb2.newUser.FromString,
          response_serializer=mensajeria__pb2.responseNewUser.SerializeToString,
      ),
      'MsgToUser': grpc.stream_stream_rpc_method_handler(
          servicer.MsgToUser,
          request_deserializer=mensajeria__pb2.msgToUser.FromString,
          response_serializer=mensajeria__pb2.msgFromUser.SerializeToString,
      ),
      'ChangeReceptor': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeReceptor,
          request_deserializer=mensajeria__pb2.ToUser.FromString,
          response_serializer=mensajeria__pb2.ToUserResponse.SerializeToString,
      ),
      'ObtainList': grpc.unary_stream_rpc_method_handler(
          servicer.ObtainList,
          request_deserializer=mensajeria__pb2.requestList.FromString,
          response_serializer=mensajeria__pb2.responseList.SerializeToString,
      ),
      'ObtainAllMsg': grpc.unary_stream_rpc_method_handler(
          servicer.ObtainAllMsg,
          request_deserializer=mensajeria__pb2.requestAllMsg.FromString,
          response_serializer=mensajeria__pb2.responseAllMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Mensajeria', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
